name: "${name}"
version: ${version}
main: "org.purpurmc.purpurextras.PurpurExtrasOG"
api-version: '1.19'
authors: [ YouHaveTrouble, NotAlexNoyle ]
description: "${description}"
commands:
  purpurextras:
    description: Command controlling PurpurExtras
    permission: purpurextras.command
